%YAML 1.2
---
$schema: 'https://json-schema.org/draft/2020-12/schema#'
$id: 'https://aquilo.schema/recipe'
title: Aquilo Recipe DAG schema
type: object
properties:
  title:
    $ref: /localize
    description: descriptive title for the recipe
  annotation:
    $ref: /localize
    description: a note of explanation or comment for the recipe
  source:
    $ref: /localize
    description: optional information describing the origin of the recipe
  nodes:
    type: array
    items:
      $ref: /recipe/node
  edges:
    type: array
    items:
      $ref: /recipe/edge
$defs:
  node:
    $id: /recipe/node
    oneOf:
      - type: object
        properties:
          kind:
            enum: [source]
          uuid:
            $ref: /uuid
          name:
            $ref: /localize
          unit:
            $ref: /source-unit
          quantity:
            type: number
          output:
            type: array
            items:
              type: string
          annotation:
            $ref: /localize
          data:
            type: string
        required: [kind, uuid, name, unit, quantity, output]
      - $ref: /operation
      - type: object
        properties:
          kind:
            enum: [sink]
          uuid:
            $ref: /uuid
          name:
            $ref: /localize
          input:
            type: array
            items:
              enum: [uno]
          annotation:
            $ref: /localize
          data:
            type: string
        required: [kind, uuid, name, input]
  edge:
    $id: /recipe/edge
    type: object
    properties:
      kind:
        enum: [edge]
      uuid:
        $ref: /uuid
      source:
        $ref: /uuid
      destination:
        $ref: /uuid
      annotation:
        $ref: /localize
      data: 
        type: string

